// NARRATION_QUALITY_GUARD_V14 — authoritative final fact narration boundary.
const PREVIOUS = global.fetch;
const GUARD_MARKER = 'NARRATION_QUALITY_GUARD_V14';
const PRIMARY_MODEL = 'openai/gpt-oss-120b';
const FALLBACK_MODEL = 'openai/gpt-oss-20b';
if (!PREVIOUS || PREVIOUS.__NARRATION_QUALITY_GUARD_V14__) { module.exports = { enabled:true, marker:GUARD_MARKER }; return; }
function isGroq(url,options){return String(url).includes('api.groq.com/openai/v1/chat/completions')&&String(options?.method||'GET').toUpperCase()==='POST';}
function isNarrationPrompt(p){return /VERIFIED FACT\s*[—-]\s*ACCURACY GROUNDING:/i.test(String(p||''));}
function sourceFrom(p){const m='VERIFIED FACT — ACCURACY GROUNDING:',s=String(p||''),i=s.indexOf(m);if(i<0)return '';const a=i+m.length,b=s.indexOf('\n\nనీ ROLE:',a);return s.slice(a,b<0?s.length:b).trim();}
function clean(s){return String(s||'').replace(/\s+/g,' ').replace(/^["“”'`]+|["“”'`]+$/g,'').replace(/[.!?।]+$/g,'').trim();}
function words(s){return String(s||'').split(/\s+/).filter(Boolean).length;}
// Each JSON field must represent exactly one narration beat. Terminal punctuation is stripped before this
// check; punctuation anywhere else means the model produced multiple beats inside one field. A '.' sitting
// directly between two digits is a decimal point (e.g. "3.5"), not a beat break, and "..." is a suspense
// pause WITHIN one beat (retention pacing), not a beat break either — both are excluded.
function oneSentence(s){s=String(s||'').trim();if(!s)return false;const t=s.replace(/(\d)\.(\d)/g,'$1$2').replace(/\.{2,}|…/g,'');return !/[.!?।]/.test(t);}
function nums(s){return (String(s||'').match(/\b\d+(?:\.\d+)?\b/g)||[]).map(Number);}
function grounded(script,source){const allowed=new Set(nums(source));for(const n of nums(script))if(!allowed.has(n))return 'unsupported number introduced';if(/(?:^|\s)कि(?:\s|$)|\b(?:hook|buildup|reveal|detail|twist|ending)\s*:/i.test(script))return 'language or structural contamination detected';const tokens=(source.toLowerCase().match(/[a-z0-9]{4,}|[ఀ-౿]{4,}/g)||[]),low=script.toLowerCase(),hits=tokens.filter(t=>low.includes(t));if(tokens.length>=3&&new Set(hits).size<2)return 'script is insufficiently grounded in verified source';return '';}
// Retention-critical clickbait clichés only — genuine suspense connectors (అసలు విషయం ఏంటంటే etc.) are now allowed and expected by makePrompt's storyteller flow, so they are NOT banned here.
function clickbait(script){return /నమ్మలేకపోతారు|లైక్ చేయండి|సబ్‌స్క్రైబ్/i.test(script)?'generic clickbait cliché detected':'';}
function parse(data,status,source){if(data?.error)return{api:true,reason:`Groq API error ${status}: ${data.error.message||data.error.code||'unknown'}`};const c=data?.choices?.[0],m=c?.message,r=m?.content;if(!r)return{reason:`model returned empty content (finish_reason=${c?.finish_reason||'unknown'})`};let o;try{o=JSON.parse(String(r).replace(/^```(?:json|text)?\s*/i,'').replace(/```$/i,'').trim());}catch{return{reason:'model returned non-JSON content'}}const k=['hook','buildup','reveal','detail','twist','ending'];if(!k.every(x=>typeof o[x]==='string'&&o[x].trim()))return{reason:'six-part field missing'};if(!k.every(x=>oneSentence(clean(o[x]))))return{reason:'field contains multiple beats'};const p=k.map((x,i)=>i?clean(o[x])+'.':clean(o[x])+'?'),script=p.join(' '),wc=words(script);if(wc<85||wc>115)return{reason:`word count ${wc} outside 85-115`};if((script.match(/\?/g)||[]).length!==1)return{reason:'expected exactly one hook question'};const cb=clickbait(script);if(cb)return{reason:cb};const g=grounded(script,source);if(g)return{reason:g};for(let i=0;i<p.length;i++)for(let j=i+1;j<p.length;j++){const a=p[i].toLowerCase().split(/\s+/),b=new Set(p[j].toLowerCase().split(/\s+/));const overlap=a.filter(x=>x.length>=4&&b.has(x)).length;if(a.length>=8&&overlap/a.length>.65)return{reason:'repetitive beats detected'};}return{script};}
function makePrompt(original,repairReason=''){const source=sourceFrom(original);const repair=repairReason?`\n\nPREVIOUS ATTEMPT FAILED: ${repairReason}. Correct that exact problem. Do not repeat it.`:'';return `నువ్వు ఒక VERIFIED FACT ని Telugu YouTube Shorts కోసం ఒక high-retention storyteller లాగా narration గా మార్చాలి — friend దగ్గర ఒక unbelievable fact వింటున్నట్టు, viewer చివరి వరకు ఆగకుండా చూసేలా.\n\nVERIFIED SOURCE:\n${source}\n\nఈ source మాత్రమే factual authority. Source లో లేని కొత్త fact, number, date, name, cause, effect, example, statistic, comparison లేదా background జోడించకూడదు. Source లో ఒక విషయం మాత్రమే ఉంటే దానినే ఆరు connected beats లో explain చేయాలి; unrelated facts కలపకూడదు.\n\nFLOW (ఖచ్చితంగా ఈ క్రమంలో ఆరు beats):\n1 Hook — curiosity పెంచే ప్రశ్న; fact ని ఇక్కడ reveal చేయకూడదు.\n2 Buildup — ఇంకా జవాబు ఇవ్వకుండా, scale/tension పెంచే ఒక్క thought.\n3 Reveal — hook కి అసలు జవాబు, ఇక్కడే మొదటిసారి core fact చెప్పాలి.\n4 Detail — source లో ఉన్న ఒక ఆశ్చర్యకరమైన నిర్దిష్ట సంఖ్య లేదా వివరం.\n5 Twist — source ఆధారంగా ఒక అదనపు, unexpected angle లేదా implication.\n6 Ending — అదే fact నుంచి వచ్చే memorable takeaway.\n\nSTRICT: EXACTLY 6 beats. EXACTLY 85-115 whitespace-separated words మొత్తం. Beat 1 మాత్రమే ప్రశ్న; మిగతావి statements. అన్ని beats ఒకే fact కి connected. Source లో లేని number/date/name/claim వద్దు. Source qualifier మార్చవద్దు. Natural spoken Telugu, friend తో మాట్లాడుతున్నట్టు — textbook లేదా news-reader టోన్ వద్దు. Technical English terms అవసరమైతే అలాగే ఉంచు; 3D ని ఎప్పుడూ మూడు D/మూడు డీగా మార్చవద్దు. Labels, CTA, title, keywords, emoji, moral, personal example, engagement request వద్దు. “అసలు విషయం ఏంటంటే”, “ఇంకా షాక్ ఏంటంటే” వంటి natural suspense connectors అవసరమైనప్పుడు మాత్రమే వాడు — ప్రతి beat కి కాదు; “నమ్మలేకపోతారు” వంటి generic clickbait వద్దు. ఒకే idea ని repeat చేయవద్దు.\n\nJSON beat rule: ప్రతి beat ఒక్క connected thought మాత్రమే కావాలి. Sentence-ending punctuation ('.', '?', '!', '।') పెట్టవద్దు — program స్వయంగా జోడిస్తుంది. Suspense pause కావాలంటే beat మధ్యలో '...' మాత్రమే వాడొచ్చు, అంతకుమించి ఏ punctuation వద్దు. Abbreviations with periods వద్దు.\n\nJSON మాత్రమే ఇవ్వాలి: {"hook":"curiosity question beat","buildup":"tension beat","reveal":"direct answer beat","detail":"surprising number/detail beat","twist":"unexpected angle beat","ending":"memorable takeaway beat"}${repair}`;}
async function request(url,options,original,model,repairReason=''){let b=JSON.parse(String(options.body||'{}'));b.model=model;b.messages=[{role:'user',content:makePrompt(original,repairReason)}];b.temperature=.15;b.reasoning_effort='low';b.include_reasoning=false;b.max_completion_tokens=2500;delete b.max_tokens;b.response_format={type:'json_schema',json_schema:{name:'telugu_fact_narration',strict:true,schema:{type:'object',properties:{hook:{type:'string'},buildup:{type:'string'},reveal:{type:'string'},detail:{type:'string'},twist:{type:'string'},ending:{type:'string'}},required:['hook','buildup','reveal','detail','twist','ending'],additionalProperties:false}}};const r=await PREVIOUS(url,{...options,body:JSON.stringify(b)});let d;try{d=await r.clone().json();}catch{throw new Error(`Groq returned non-JSON response (HTTP ${r.status})`);}if(!r.ok||d?.error){const e=new Error(`Groq API error ${r.status}: ${d?.error?.message||d?.error?.code||'unknown'}`);e.status=r.status;e.retryAfter=Number(r.headers.get('retry-after')||0);throw e;}return{r,d};}
const sleep=ms=>new Promise(x=>setTimeout(x,ms));
async function guardedFetch(url,options={}){if(!isGroq(url,options))return PREVIOUS(url,options);let b;try{b=JSON.parse(String(options.body||'{}'));}catch{return PREVIOUS(url,options);}const last=Array.isArray(b.messages)?b.messages[b.messages.length-1]:null,original=last?.content||'';if(!isNarrationPrompt(original))return PREVIOUS(url,options);const source=sourceFrom(original);if(!source)throw new Error('Clean fact narration failed — verified source missing');console.log(`${GUARD_MARKER}: intercepted final narration request.`);let model=PRIMARY_MODEL,lastReason='unknown';for(let attempt=0;attempt<6;attempt++){try{const x=await request(url,options,original,model,lastReason==='unknown'?'':lastReason),v=parse(x.d,x.r.status,source);if(v.script){x.d.choices[0].message.content=v.script;x.d.choices[0].finish_reason='stop';console.log(`${GUARD_MARKER}: FINAL FACT NARRATION accepted — ${words(v.script)} words, 6-beat retention arc, model=${model}.`);return new Response(JSON.stringify(x.d),{status:x.r.status,statusText:x.r.statusText,headers:x.r.headers});}lastReason=v.reason;console.log(`${GUARD_MARKER}: validation ${attempt+1}/6 rejected — ${lastReason}`);}catch(e){lastReason=e.message;const transient=[429,498,500,502,503,504].includes(e.status);if(!transient)throw new Error(`Clean fact narration failed — ${lastReason}`);if(model===PRIMARY_MODEL&&attempt>=1){model=FALLBACK_MODEL;console.log(`${GUARD_MARKER}: switching to ${model}.`);}const delay=e.retryAfter?Math.min(e.retryAfter*1000,60000):Math.min(8000*Math.pow(2,attempt),30000);await sleep(delay);}}throw new Error(`Clean fact narration failed after bounded attempts — ${lastReason}`);}
global.fetch=guardedFetch;guardedFetch.__NARRATION_QUALITY_GUARD_V14__=true;module.exports={enabled:true,marker:GUARD_MARKER};console.log(`${GUARD_MARKER}: enabled — strict grounded six-beat retention-style fact narration guard loaded.`);
