// NARRATION_QUALITY_GUARD_V14 — authoritative final fact narration boundary.
const PREVIOUS = global.fetch;
const GUARD_MARKER = 'NARRATION_QUALITY_GUARD_V14';
const PRIMARY_MODEL = 'openai/gpt-oss-120b';
const FALLBACK_MODEL = 'openai/gpt-oss-20b';
if (!PREVIOUS || PREVIOUS.__NARRATION_QUALITY_GUARD_V14__) { module.exports = { enabled:true, marker:GUARD_MARKER }; return; }
function isGroq(url,options){return String(url).includes('api.groq.com/openai/v1/chat/completions')&&String(options?.method||'GET').toUpperCase()==='POST';}
function isNarrationPrompt(p){return /VERIFIED FACT\s*[—-]\s*ACCURACY GROUNDING:/i.test(String(p||''));}
function sourceFrom(p){const m='VERIFIED FACT — ACCURACY GROUNDING:',s=String(p||''),i=s.indexOf(m);if(i<0)return '';const a=i+m.length,b=s.indexOf('\n\nనీ ROLE:',a);return s.slice(a,b<0?s.length:b).trim();}
function clean(s){return String(s||'').replace(/\s+/g,' ').replace(/^["“”'`]+|["“”'`]+$/g,'').replace(/[.!?।]+$/g,'').trim();}
function words(s){return String(s||'').split(/\s+/).filter(Boolean).length;}
// Each JSON field must represent exactly one sentence. Terminal punctuation is stripped before this check;
// punctuation anywhere else means the model produced multiple sentences inside one field.
function oneSentence(s){s=String(s||'').trim();return !!s&&!/[.!?।]/.test(s);}
function nums(s){return (String(s||'').match(/\b\d+(?:\.\d+)?\b/g)||[]).map(Number);}
function grounded(script,source){const allowed=new Set(nums(source));for(const n of nums(script))if(!allowed.has(n))return 'unsupported number introduced';if(/(?:^|\s)कि(?:\s|$)|\b(?:hook|fact|explanation|context|meaning|conclusion)\s*:/i.test(script))return 'language or structural contamination detected';const tokens=(source.toLowerCase().match(/[a-z0-9]{4,}|[\u0c00-\u0c7f]{4,}/g)||[]),low=script.toLowerCase(),hits=tokens.filter(t=>low.includes(t));if(tokens.length>=3&&new Set(hits).size<2)return 'script is insufficiently grounded in verified source';return '';}
function parse(data,status,source){if(data?.error)return{api:true,reason:`Groq API error ${status}: ${data.error.message||data.error.code||'unknown'}`};const c=data?.choices?.[0],m=c?.message,r=m?.content;if(!r)return{reason:`model returned empty content (finish_reason=${c?.finish_reason||'unknown'})`};let o;try{o=JSON.parse(String(r).replace(/^```(?:json|text)?\s*/i,'').replace(/```$/i,'').trim());}catch{return{reason:'model returned non-JSON content'}}const k=['hook','fact','explanation','context','meaning','conclusion'];if(!k.every(x=>typeof o[x]==='string'&&o[x].trim()))return{reason:'six-part field missing'};if(!k.every(x=>oneSentence(clean(o[x]))))return{reason:'field contains multiple sentences'};const p=k.map((x,i)=>i?clean(o[x])+'.':clean(o[x])+'?'),script=p.join(' '),wc=words(script);if(wc<85||wc>115)return{reason:`word count ${wc} outside 85-115`};if((script.match(/\?/g)||[]).length!==1)return{reason:'expected exactly one hook question'};if(/అసలు విషయం ఏంటంటే|ఇంకా షాక్ ఏంటంటే|ఇది వింటే షాక్|నమ్మలేకపోతారు|షాక్ అవుతారు|ఊహించండి|కానీ\.\.\.|అయితే\.\.\./i.test(script))return{reason:'storyteller filler detected'};const g=grounded(script,source);if(g)return{reason:g};for(let i=0;i<p.length;i++)for(let j=i+1;j<p.length;j++){const a=p[i].toLowerCase().split(/\s+/),b=new Set(p[j].toLowerCase().split(/\s+/));const overlap=a.filter(x=>x.length>=4&&b.has(x)).length;if(a.length>=8&&overlap/a.length>.65)return{reason:'repetitive sentences detected'};}return{script};}
function makePrompt(original,repairReason=''){const source=sourceFrom(original);const repair=repairReason?`\n\nPREVIOUS ATTEMPT FAILED: ${repairReason}. Correct that exact problem. Do not repeat it.`:'';return `నువ్వు ఒక VERIFIED FACT ని Telugu YouTube Shorts కోసం సహజమైన, అర్థవంతమైన fact-explainer narration గా మార్చాలి.\n\nVERIFIED SOURCE:\n${source}\n\nఈ source మాత్రమే factual authority. Source లో లేని కొత్త fact, number, date, name, cause, effect, example, statistic, comparison లేదా background జోడించకూడదు. Source లో ఒక విషయం మాత్రమే ఉంటే దానినే ఆరు connected sentences లో explain చేయాలి; unrelated facts కలపకూడదు.\n\nఇది STORY కాదు. Fake suspense, shock language, dramatic reveal, twist, cliffhanger, generic viral-template wording వద్దు. ఒక knowledgeable person ఒక verified fact ని viewer కి స్పష్టంగా explain చేస్తున్నట్టు ఉండాలి.\n\nFLOW: 1 Hook — సహజమైన curiosity question. 2 Fact — hook కి నేరుగా సమాధానం. 3 Explanation — core concept ని సులభంగా explain చేయి. 4 Important context — source లో ఉన్న relevant date/background/condition మాత్రమే. 5 Meaning — ముందు చెప్పిన facts ఎందుకు significantో source ఆధారంగా logically connect చేయి. 6 Conclusion — అదే fact నుంచి వచ్చే clear takeaway.\n\nSTRICT: EXACTLY 6 complete sentences. EXACTLY 85-115 whitespace-separated words. Sentence 1 మాత్రమే question. Sentence 2 hook కి direct answer. అన్ని sentences ఒకే fact కి connected. Source లో లేని number/date/name/claim వద్దు. Source qualifier మార్చవద్దు. Natural spoken Telugu. Technical English terms అవసరమైతే అలాగే ఉంచు; 3D ని ఎప్పుడూ మూడు D/మూడు డీగా మార్చవద్దు. Labels, CTA, title, keywords, emoji, moral, personal example, engagement request వద్దు. “అసలు విషయం ఏంటంటే”, “ఇంకా షాక్ ఏంటంటే”, “ఇది వింటే షాక్”, “నమ్మలేకపోతారు” వంటి filler వద్దు. ఒకే idea ని repeat చేయవద్దు.\n\nJSON field punctuation rule: ప్రతి field లో EXACTLY ONE sentence మాత్రమే ఉండాలి. ఏ field లోనూ internal '.', '?', '!' లేదా '।' పెట్టవద్దు. Sentence-ending punctuation కూడా పెట్టకూడదు; program స్వయంగా sentence punctuation జోడిస్తుంది. Hook field కూడా question mark లేకుండా question wording మాత్రమే ఇవ్వాలి. Abbreviations with periods వద్దు; అవసరమైతే వాటిని period లేకుండా రాయాలి. JSON మాత్రమే ఇవ్వాలి: {"hook":"one sentence without punctuation","fact":"one sentence without punctuation","explanation":"one sentence without punctuation","context":"one sentence without punctuation","meaning":"one sentence without punctuation","conclusion":"one sentence without punctuation"}${repair}`;}
async function request(url,options,original,model,repairReason=''){let b=JSON.parse(String(options.body||'{}'));b.model=model;b.messages=[{role:'user',content:makePrompt(original,repairReason)}];b.temperature=.1;b.reasoning_effort='low';b.include_reasoning=false;b.max_completion_tokens=2500;delete b.max_tokens;b.response_format={type:'json_schema',json_schema:{name:'telugu_fact_narration',strict:true,schema:{type:'object',properties:{hook:{type:'string'},fact:{type:'string'},explanation:{type:'string'},context:{type:'string'},meaning:{type:'string'},conclusion:{type:'string'}},required:['hook','fact','explanation','context','meaning','conclusion'],additionalProperties:false}}};const r=await PREVIOUS(url,{...options,body:JSON.stringify(b)});let d;try{d=await r.clone().json();}catch{throw new Error(`Groq returned non-JSON response (HTTP ${r.status})`);}if(!r.ok||d?.error){const e=new Error(`Groq API error ${r.status}: ${d?.error?.message||d?.error?.code||'unknown'}`);e.status=r.status;e.retryAfter=Number(r.headers.get('retry-after')||0);throw e;}return{r,d};}
const sleep=ms=>new Promise(x=>setTimeout(x,ms));
async function guardedFetch(url,options={}){if(!isGroq(url,options))return PREVIOUS(url,options);let b;try{b=JSON.parse(String(options.body||'{}'));}catch{return PREVIOUS(url,options);}const last=Array.isArray(b.messages)?b.messages[b.messages.length-1]:null,original=last?.content||'';if(!isNarrationPrompt(original))return PREVIOUS(url,options);const source=sourceFrom(original);if(!source)throw new Error('Clean fact narration failed — verified source missing');console.log(`${GUARD_MARKER}: intercepted final narration request.`);let model=PRIMARY_MODEL,lastReason='unknown';for(let attempt=0;attempt<6;attempt++){try{const x=await request(url,options,original,model,lastReason==='unknown'?'':lastReason),v=parse(x.d,x.r.status,source);if(v.script){x.d.choices[0].message.content=v.script;x.d.choices[0].finish_reason='stop';console.log(`${GUARD_MARKER}: FINAL FACT NARRATION accepted — ${words(v.script)} words, 6 connected sentences, model=${model}.`);return new Response(JSON.stringify(x.d),{status:x.r.status,statusText:x.r.statusText,headers:x.r.headers});}lastReason=v.reason;console.log(`${GUARD_MARKER}: validation ${attempt+1}/6 rejected — ${lastReason}`);}catch(e){lastReason=e.message;const transient=[429,498,500,502,503,504].includes(e.status);if(!transient)throw new Error(`Clean fact narration failed — ${lastReason}`);if(model===PRIMARY_MODEL&&attempt>=1){model=FALLBACK_MODEL;console.log(`${GUARD_MARKER}: switching to ${model}.`);}const delay=e.retryAfter?Math.min(e.retryAfter*1000,60000):Math.min(8000*Math.pow(2,attempt),30000);await sleep(delay);}}throw new Error(`Clean fact narration failed after bounded attempts — ${lastReason}`);}
global.fetch=guardedFetch;guardedFetch.__NARRATION_QUALITY_GUARD_V14__=true;module.exports={enabled:true,marker:GUARD_MARKER};console.log(`${GUARD_MARKER}: enabled — strict grounded six-sentence fact narration guard loaded.`);
