const fs = require('fs');
const path = require('path');
const child = require('child_process');

// Stable launcher: index.js remains the single source of truth.
const SOURCE = path.join(__dirname, 'index.js');
const RUNTIME = path.join(__dirname, '.index.runtime.js');
const QUALITY_GUARD = path.join(__dirname, 'narration_quality_guard_v14.js');
const EXPECTED_GUARD = 'NARRATION_QUALITY_GUARD_V14';

child.execFileSync(process.execPath, ['--check', SOURCE], { stdio: 'inherit' });
child.execFileSync(process.execPath, ['--check', QUALITY_GUARD], { stdio: 'inherit' });
fs.copyFileSync(SOURCE, RUNTIME);

let runtimeSource = fs.readFileSync(RUNTIME, 'utf8');
const OLD_BRAND = "text='TELUGU ECHO'";
const NEW_BRAND = "text='FACTVERSE TELUGU'";
if (!runtimeSource.includes(OLD_BRAND)) throw new Error('Branding preflight failed: TELUGU ECHO marker not found in index.js');
runtimeSource = runtimeSource.replace(OLD_BRAND, NEW_BRAND);

// FINAL NARRATION INTEGRITY BOUNDARY
// The guard creates exactly six semantic sentences. index.js historically
// ran ensureSentenceBreaks() afterwards to protect Google TTS from long
// sentences. That safety function is allowed to INSERT periods, which turned
// a valid six-sentence fact script into 7-8 sentences. It must never be
// allowed to rewrite the final narration structure. Google TTS is handled
// safely by the existing per-sentence/clause synthesis layer instead.
const oldEnsureCall = 'script = ensureSentenceBreaks(script);';
const newEnsureCall = "script = script.replace(/\\n+/g, ' ').replace(/[ \\t]+/g, ' ').trim();";
if (!runtimeSource.includes(oldEnsureCall)) {
  throw new Error('Narration integrity preflight failed: ensureSentenceBreaks call not found. Refusing to run.');
}
runtimeSource = runtimeSource.replace(oldEnsureCall, newEnsureCall);

// Add a deterministic final six-sentence check immediately before metadata
// generation. This catches any downstream punctuation pass that accidentally
// merges or splits the six-part narration. Ellipses are ignored when counting
// sentence-ending punctuation.
const integrityMarker = '  // CALL C: metadata (title/keywords/hook) extracted from the FINISHED,';
const integrityCode = `  // FINAL FACT SCRIPT INTEGRITY CHECK: the narration generated by the guard
  // must remain exactly six sentences all the way to metadata/TTS.
  const countFinalNarrationSentences = (text) => {
    const normalized = String(text || '').replace(/\\.\\.\\./g, '');
    return (normalized.match(/[.!?।]+/g) || []).length;
  };
  const finalNarrationSentenceCount = countFinalNarrationSentences(script);
  if (finalNarrationSentenceCount !== 6) {
    throw new Error(\`Final narration integrity failure: expected exactly 6 sentences, got \${finalNarrationSentenceCount}. Refusing to build/upload a structurally corrupted script.\`);
  }
  if (/\\b\\d{4,}\\b|\\b\\d{1,3}(?:,\\d{3})+\\b/.test(script)) {
    throw new Error('Final narration integrity failure: ASCII large-number digits reached the publish boundary. Refusing to send digit-by-digit pronunciation to TTS.');
  }

`;
if (!runtimeSource.includes(integrityMarker)) {
  throw new Error('Narration integrity preflight failed: metadata boundary not found. Refusing to run.');
}
runtimeSource = runtimeSource.replace(integrityMarker, integrityCode + integrityMarker);

fs.writeFileSync(RUNTIME, runtimeSource, 'utf8');
child.execFileSync(process.execPath, ['--check', RUNTIME], { stdio: 'inherit' });

const NATIVE_FETCH = global.fetch;
if (!NATIVE_FETCH) throw new Error('Global fetch is unavailable.');

const NARRATION_KEYS = ['hook', 'fact', 'explanation', 'context', 'meaning', 'conclusion'];
const NUMBER_WORDS = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten'];

function normalizeTechnicalSpeech(text) {
  let t = String(text || '');
  // Generic technical-number pronunciation: 3D/3-D/3 D -> three D,
  // 4K -> four K, 5G -> five G, etc. This is a speech-boundary rule, not a
  // one-off fix for a single topic.
  t = t.replace(/\b(10|[0-9])\s*[- ]?([dDgGkK])\b/g, (_, n, letter) => {
    const value = Number(n);
    return value >= 0 && value <= 10 ? `${NUMBER_WORDS[value]} ${letter.toUpperCase()}` : `${n} ${letter.toUpperCase()}`;
  });
  return t;
}
function extractSpeechText(value) {
  let t = String(value || '').trim();
  if (!t) return '';
  try {
    const parsed = JSON.parse(t.replace(/^```(?:json)?\s*/i, '').replace(/```$/i, '').trim());
    if (parsed && typeof parsed === 'object' && NARRATION_KEYS.some(k => typeof parsed[k] === 'string')) {
      t = NARRATION_KEYS.map(k => parsed[k]).filter(v => typeof v === 'string' && v.trim()).join(' ');
    }
  } catch (_) {}
  t = t.replace(/^```(?:json|text)?\s*/i, '').replace(/```$/i, '').replace(/[{}]/g, '');
  t = t.replace(/(?:^|[\n\r])\s*["']?(?:hook|fact|explanation|context|meaning|conclusion)["']?\s*[:：-]\s*/gim, '\n');
  t = t.replace(/(?:^|[\n\r])\s*(?:హుక్|ఫ్యాక్ట్|వివరణ|సందర్భం|అర్థం|ముగింపు)\s*[:：-]\s*/gim, '\n');
  return normalizeTechnicalSpeech(t.replace(/\s+/g, ' ').trim());
}
function sanitizeTtsBody(body) {
  if (!body || !body.input) return body;
  const out = { ...body, input: { ...body.input } };
  if (typeof out.input.text === 'string') out.input.text = extractSpeechText(out.input.text);
  if (typeof out.input.ssml === 'string') out.input.ssml = extractSpeechText(out.input.ssml);
  const spoken = typeof out.input.text === 'string' ? out.input.text : out.input.ssml;
  if (!spoken) throw new Error('TTS preflight rejected empty speech text.');
  if (/(?:^|\s)(?:hook|fact|explanation|context|meaning|conclusion)\s*:/i.test(spoken)) throw new Error('TTS preflight rejected structural narration labels.');
  if (/\b(?:NaN|undefined|null)\b/i.test(spoken)) throw new Error('TTS preflight rejected invalid narration token.');
  return out;
}

global.fetch = async (url, options = {}) => {
  const urlString = String(url);
  if (urlString.includes('texttospeech.googleapis.com')) {
    const body = sanitizeTtsBody(JSON.parse(String(options.body || '{}')));
    return NATIVE_FETCH(url, { ...options, body: JSON.stringify(body) });
  }
  if (!urlString.includes('api.groq.com/openai/v1/chat/completions')) return NATIVE_FETCH(url, options);

  let body;
  try { body = JSON.parse(String(options.body || '{}')); } catch (_) { return NATIVE_FETCH(url, options); }
  const messages = Array.isArray(body.messages) ? body.messages : [];
  const last = messages[messages.length - 1];
  const prompt = last && typeof last.content === 'string' ? last.content : '';

  const isOriginalFinalNarration = /VERIFIED FACT\s*[—-]\s*ACCURACY GROUNDING:/i.test(prompt)
    && (/STORY BEATS/i.test(prompt) || /high-retention storyteller/i.test(prompt) || /final narration/i.test(prompt));
  const isGuardedFinalNarration = /VERIFIED SOURCE:/i.test(prompt)
    && /FACT-EXPLAINER/i.test(prompt)
    && /EXACTLY 6 complete sentences/i.test(prompt);
  const isFinalNarration = isOriginalFinalNarration || isGuardedFinalNarration;

  if (isFinalNarration) {
    body.model = 'openai/gpt-oss-120b';
    const requested = Number(body.max_completion_tokens);
    body.max_completion_tokens = Number.isFinite(requested) && requested > 0 ? requested : 4000;
    delete body.max_tokens;
    body.reasoning_effort = 'low';
    body.include_reasoning = false;
  } else {
    body.model = 'openai/gpt-oss-20b';
    body.max_completion_tokens = 2000;
    delete body.max_tokens;
    body.reasoning_effort = 'low';
    body.include_reasoning = false;
  }

  return NATIVE_FETCH(url, { ...options, body: JSON.stringify(body) });
};

const guard = require(QUALITY_GUARD);
if (!guard || guard.marker !== EXPECTED_GUARD) throw new Error(`Narration quality guard ${EXPECTED_GUARD} failed to load — refusing to run the video pipeline.`);
console.log(`${EXPECTED_GUARD}: source + runtime syntax checks passed; final six-sentence fact narration guard loaded with downstream integrity protection.`);
require(RUNTIME);
