const fs = require('fs');
const path = require('path');
const child = require('child_process');

const V8 = path.join(__dirname, 'runtime_llm_router_v8.js');
const RUNTIME = path.join(__dirname, '.index.runtime.v8.js');

// V8 is the provider/fresh-topic patcher. Run it in PATCH_ONLY mode so V10
// can safely harden the generated runtime before the actual application runs.
child.execFileSync(process.execPath, [V8], {
  stdio: 'inherit',
  env: { ...process.env, LLM_ROUTER_PATCH_ONLY: '1' }
});

let source = fs.readFileSync(RUNTIME, 'utf8');

function mustChange(re, replacement, label) {
  const before = source;
  source = source.replace(re, replacement);
  if (source === before) throw new Error('V10 patch anchor not found: ' + label);
}

// Hard target for a real 50-60 second Telugu narration. The CTA is appended
// separately, so the content itself must already be substantial enough.
for (const category of ['mindblowing','psychology','earth_space','animal','money','history','human_body','technology','food','ocean']) {
  mustChange(
    new RegExp(category + ':\\s*\\{\\s*min:\\s*85,\\s*max:\\s*115\\s*\\}', 'g'),
    category + ': { min: 88, max: 105 }',
    'word target ' + category
  );
}

// Mandatory spoken CTA for every video.
mustChange(
  /const CTA_VARIATIONS = \[[\s\S]*?\];/,
  "const CTA_VARIATIONS = ['వీడియో నచ్చితే లైక్ అండ్ షేర్ చేయండి, మరిన్ని ఇలాంటి వీడియోల కోసం సబ్‌స్క్రైబ్ చేయండి.'];",
  'mandatory CTA'
);

// Allow a final TTS-rate correction without changing the normal speaking rate.
mustChange(
  /const SPEAKING_RATE = [^;]+;/,
  'const SPEAKING_RATE = Number(globalThis.__TELUGU_TTS_RATE || 0.98);',
  'speaking rate'
);

// Do not accept short scripts. Make the retry counter and condition truthful.
mustChange(
  /for \(let retryAttempt = 1; retryAttempt <= \d+ && \([\s\S]*?\); retryAttempt\+\+\)/,
  'for (let retryAttempt = 1; retryAttempt <= 4 && (wordCount < target.min || wordCount > target.max || bestWordCount < target.min || bestWordCount > MAX_SAFE_WORDS); retryAttempt++)',
  'script retry loop'
);

source = source.replace(/retry \$\{retryAttempt\}\/\d+/g, 'retry ${retryAttempt}/4');

mustChange(
  /const MIN_VIABLE_WORDS = \d+;/,
  'const MIN_VIABLE_WORDS = target.min;',
  'minimum viable words'
);

// Replace the old "use best short attempt" warning with a hard failure.
mustChange(
  /if \(bestWordCount < target\.min - 15\) \{[\s\S]*?\n  \} else if \(bestWordCount > MAX_SAFE_WORDS\) \{/,
  "if (bestWordCount < target.min) {\n    throw new Error(`SCRIPT_LENGTH_GUARD_FAILED: after 4 retries narration is ${bestWordCount} words; target is ${target.min}-${target.max}. Refusing to build a short video.`);\n  } else if (bestWordCount > MAX_SAFE_WORDS) {",
  'short-script hard fail'
);

// Add a stronger instruction directly to the narration prompt without
// depending on one exact multiline string from a previous patch.
mustChange(
  /const narrationPrompt = buildNarrationPrompt\(category, recentTitles, outline, beats\);/,
  "const narrationPrompt = buildNarrationPrompt(category, recentTitles, outline, beats) + '\\n\\nHARD LENGTH REQUIREMENT: produce 88-105 spoken Telugu words. Expand every verified beat naturally. Do not stop early. CTA is added separately.';",
  'narration length instruction'
);

// The provider router generated by V8 already uses max_completion_tokens for
// OpenAI and a 3000-token Groq budget. Keep this defensive replacement for
// older generated runtimes too; unlike V9 it is regex-based and idempotent.
source = source.replace(
  /else body\.max_tokens = p\.name === 'groq-20b' \? 1400 : 1800;/g,
  "else body.max_tokens = p.kind === 'groq' ? 3000 : 2200;"
);

// Hard 50-60 second measured narration guard. If the first generation is too
// short/long, regenerate content. If it is still outside the safe window,
// make one TTS-rate correction. Never upload outside 50-60 seconds.
mustChange(
  /  const ctaSentence = pickCTA\(runCount\);\n  const \{ title, hookEmoji, script \} = await generateContent\(category, usedTitles, outline, ctaSentence\);\n  const allSentences = splitIntoSentences\(script\);\n  let \{ audioPath, sentenceDurations, silenceGap \} = await generateAudioForScript\(allSentences\);/,
  `  const ctaSentence = pickCTA(runCount);
  let title, hookEmoji, script, allSentences, audioPath, sentenceDurations, silenceGap;
  let measuredNarrationDuration = 0;
  for (let contentAudioAttempt = 1; contentAudioAttempt <= 4; contentAudioAttempt++) {
    const generated = await generateContent(category, usedTitles, outline, ctaSentence);
    title = generated.title;
    hookEmoji = generated.hookEmoji;
    script = generated.script;
    allSentences = splitIntoSentences(script);
    const generatedAudio = await generateAudioForScript(allSentences);
    audioPath = generatedAudio.audioPath;
    sentenceDurations = generatedAudio.sentenceDurations;
    silenceGap = generatedAudio.silenceGap;
    measuredNarrationDuration = getAudioDuration(audioPath);
    log('Duration guard attempt ' + contentAudioAttempt + ': narration=' + measuredNarrationDuration.toFixed(2) + 's (target 50-60s final video).');
    if (measuredNarrationDuration >= 49.7 && measuredNarrationDuration <= 59.7) break;
    log('WARNING: narration duration outside safe 49.7-59.7s — regenerating content before continuing.');
  }
  if (measuredNarrationDuration < 49.7 || measuredNarrationDuration > 59.7) {
    const targetDuration = 54.7;
    const correctedRate = Math.max(0.75, Math.min(1.20, 0.98 * measuredNarrationDuration / targetDuration));
    globalThis.__TELUGU_TTS_RATE = correctedRate;
    log('Applying final TTS duration correction: speakingRate=' + correctedRate.toFixed(3));
    const correctedAudio = await generateAudioForScript(allSentences);
    audioPath = correctedAudio.audioPath;
    sentenceDurations = correctedAudio.sentenceDurations;
    silenceGap = correctedAudio.silenceGap;
    measuredNarrationDuration = getAudioDuration(audioPath);
    log('Final narration duration after TTS correction: ' + measuredNarrationDuration.toFixed(2) + 's.');
  }
  if (measuredNarrationDuration < 49.7 || measuredNarrationDuration > 59.7) {
    throw new Error('VIDEO_DURATION_GUARD_FAILED: final narration is ' + measuredNarrationDuration.toFixed(2) + 's; refusing to upload outside the required 50-60s window.');
  }`,
  'hard 50-60s duration guard'
);

child.execFileSync(process.execPath, ['--check', RUNTIME], { stdio: 'inherit' });
fs.writeFileSync(RUNTIME, source, 'utf8');
child.execFileSync(process.execPath, ['--check', RUNTIME], { stdio: 'inherit' });
console.log('LLM_ROUTER_V10: V8 provider base + idempotent 88-105 word target + hard 50-60s duration guard + mandatory CTA applied successfully.');
require(RUNTIME);
